# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false
# Parchment mappings - https://parchmentmc.org/docs/getting-started
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
## Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.249
neo_version_range=[21.1,)
loader_version_range=[4,)
## Mod Properties
mod_id=armor_cosmetic
mod_name=Armor Cosmetic
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.skd.armorcosmetic
mod_authors=skd
mod_description=This mod allows you to wear two sets of armor, one for display, one for function. You can also hide armor for your skin. For PVP, you can stop the mod from functioning on your client side.
